### ISSUE TITLE
CentOS7 安装失败

### ISSUE THREAD

**Issue by LanserShi** [iptux-src/iptux#204]
CMake Warning (dev) at build/src/googletest-src/CMakeLists.txt:3 (project):
  Policy CMP0048 is not set: project() command manages VERSION variables.
  Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The following variable(s) would be set to empty:

    PROJECT_VERSION
    PROJECT_VERSION_MAJOR
    PROJECT_VERSION_MINOR
    PROJECT_VERSION_PATCH
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at build/src/googletest-src/googlemock/CMakeLists.txt:40 (project):
  Policy CMP0048 is not set: project() command manages VERSION variables.
  Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The following variable(s) would be set to empty:

    PROJECT_VERSION
    PROJECT_VERSION_MAJOR
    PROJECT_VERSION_MINOR
    PROJECT_VERSION_PATCH
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at build/src/googletest-src/googletest/CMakeLists.txt:47 (project):
  Policy CMP0048 is not set: project() command manages VERSION variables.
  Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The following variable(s) would be set to empty:

    PROJECT_VERSION
    PROJECT_VERSION_MAJOR
    PROJECT_VERSION_MINOR
    PROJECT_VERSION_PATCH
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found PythonInterp: /usr/bin/python (found version "2.7.5") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Checking for modules 'glib-2.0>=2.32.0;gthread-2.0>=2.14.0;gtk+-3.0>=3.12;jsoncpp>=1.0'
--   
--   
CMake Error at /usr/share/cmake3/Modules/FindPkgConfig.cmake:424 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake3/Modules/FindPkgConfig.cmake:597 (_pkg_check_modules_internal)
  src/iptux/CMakeLists.txt:1 (pkg_check_modules)

-- Configuring incomplete, errors occurred!
See also "/home/song/download/iptux/build/CMakeFiles/CMakeOutput.log".
See also "/home/song/download/iptux/build/CMakeFiles/CMakeError.log".

[CMakeError.log](https://github.com/iptux-src/iptux/files/1918264/CMakeError.log)
[CMakeOutput.log](https://github.com/iptux-src/iptux/files/1918265/CMakeOutput.log)

**Comment by lidaobing** [comment]
check https://github.com/iptux-src/iptux/wiki/CentOS-and-RHEL%E5%AE%89%E8%A3%85%E6%96%B9%E5%BC%8F
