### ISSUE TITLE
Can't install on CentOS 7

### ISSUE THREAD

**Issue by santhgates** [iptux-src/iptux#276]
The installation steps in the link https://github.com/iptux-src/iptux/wiki/CentOS-and-RHEL%E5%AE%89%E8%A3%85%E6%96%B9%E5%BC%8F doesn't work anymore and it says 

> CMake Error: The source directory "/Downloads/iptux" does not appear to contain CMakeLists.txt.

Can you please update the installation steps for installing in CentOS 7?

**Comment by lidaobing** [comment]
https://github.com/iptux-src/iptux/wiki/CentOS-and-RHEL%E5%AE%89%E8%A3%85%E6%96%B9%E5%BC%8F(0.7.*) it only works for 0.7.*, so I updated the title and content
