### ISSUE TITLE
iptux: error while loading shared libraries: libiptux-core.so.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by verigle** [iptux-src/iptux#298]
I build iptux from source 
but when  iptux is runing,it show that iptux: error while loading shared libraries: libiptux-core.so.0: cannot open shared object file: No such file or directory

**Comment by jpepper2008** [comment]
I have the same problem (Ubuntu 18.04)

**Comment by jpepper2008** [comment]
The linking issue can be solved by running:
`sudo /sbin/ldconfig -v`

after that, Ubuntu will be able to find libiptux-core.so.0.

Now iptux runs fine, but I can't get it to close!
`(iptux:3223): Gtk-CRITICAL **: 23:55:46.332: gtk_main_quit: assertion 'main_loops != NULL' failed
`

**Comment by lidaobing** [comment]
@jpepper2008 `libgoogle-glog-dev` issues fixed in README.md
