### ISSUE TITLE
I use the latest version.when send file.get error

### ISSUE THREAD

**Issue by liulanghaitun** [iptux-src/iptux#300]
*** Aborted at 1586066606 (unix time) try "date -d @1586066606" if you are using GNU date ***
PC: @     0x7f7983560420 (unknown)
*** SIGSEGV (@0x130) received by PID 19675 (TID 0x7f79817f9940) from PID 304; stack trace: ***
    @     0x7f798287c9c9 (unknown)
    @     0x7f79825c00b0 (unknown)
    @     0x7f7983560420 (unknown)
    @     0x556dd2e2e9f4 iptux::transModelFillFromTransFileModel()
    @     0x556dd2e1fe9f iptux::MainWindow::UpdateItemToTransTree()
    @     0x556dd2e24f55 iptux::MainWindow::processEventInMainThread()
    @     0x556dd2e258bf iptux::MainWindow::processEventCallback()
    @     0x7f7982da1389 (unknown)
    @     0x7f7982a22411 g_main_context_dispatch
    @     0x7f7982a227d8 (unknown)
    @     0x7f7982a2286f g_main_context_iteration
    @     0x7f7982c1d3ed g_application_run
    @     0x556dd2e17131 main
    @     0x7f7982416e9b __libc_start_main
    @     0x556dd2e1734a _start
Segmentation fault

**Comment by lidaobing** [comment]
This issue has been fixed, please have a check, thx
