### ISSUE TITLE
forward Debian bug  #967537 iptux: depends on deprecated GTK 2

### ISSUE THREAD

**Issue by atzlinux** [iptux-src/iptux#307]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=967537

**Comment by lidaobing** [comment]
@atzlinux the master branch is depending on GTK3

**Comment by atzlinux** [comment]
Could you release the new version of iptux? add a tag is also ok.

If do so, the Debian package of iptux is more easy to update to this new upstream version.

**Comment by lidaobing** [comment]
@atzlinux 

iptux is out of maintain.
and anyway as you wish, I released a alpha version: https://github.com/iptux-src/iptux/releases/tag/v0.8.0-a1
