### ISSUE TITLE
File Size always zero in linux

### ISSUE THREAD

**Issue by aswin1980** [iptux-src/iptux#31]
Hi, I have downloaded the latest master release. There seems to be an issue when I select single file. The file size is always zero and files are not getting transfered.

I was able to debug the issue. In AnalogFs.cpp you are calling a function called ftwsize. To this function the file path is sent which actually contains the filename with full path. when opendir is called, which actually files as it is a regular file and not directory. hence the bytes always  returns 0(file->filesize = afs.ftwsize(file->filepath);   //不得不计算文件长度了). Sorry I couldnt interpret your comments.

Could you fix this. Here is the change i have made. 

int64_t AnalogFS::ftwsize(const char *dir_name)
{
        int64_t sumsize = 0;
        struct stat64 st;
        if(stat64(dir_name, &st) == -1) {
                return sumsize;
        }
        if(S_ISREG(st.st_mode)) {
                sumsize += st.st_size;
                return sumsize;
        }
        DIR* dir = opendir(dir_name);
        if(dir == NULL) {
                pwarning(_("opendir on \"%s\" failed: %s"), dir_name, strerror(errno));
                return 0;
        }

        struct dirent *dirt;

        while(dirt = readdir(dir)) {
                if(strcmp(dirt->d_name, ".") == 0) {
                        continue;
                }
                if(strcmp(dirt->d_name, "..") == 0) {
                        continue;
                }
                char tpath[MAX_PATHLEN];
                strcpy(tpath, dir_name);
                mergepath(tpath, dirt->d_name);
                struct stat64 st;
                if(stat64(tpath, &st) == -1) {
                        continue;
                }
                if(S_ISDIR(st.st_mode)) {
                        sumsize += ftwsize(tpath);
                } else if(S_ISREG(st.st_mode)) {
                        sumsize += st.st_size;
                } else {
                        // ignore other files
                }

        }
        return sumsize;
}

**Comment by anthonyfok** [comment]
@aswin1980, 感谢你的贡献。

你报告的问题似乎跟后来 @fzhq1970 报告的 Issue #33 相同，不过因为 @fzhq1970 的修改，由 @gxcast 做成了补丁，提交了 Pull Request #35，这样 iptux 的维护者就很容易地合并了，请测试在 Git HEAD 里的最新版本，谢谢！

@lidaobing, 麻烦你有空的时候关闭这个 Issue？谢谢！
