### ISSUE TITLE
发现bug

### ISSUE THREAD

**Issue by fzhq1970** [iptux-src/iptux#33]
在DialogBase.ccp的176-188
 if (stat64((const char _)tlist->data, &st) == -1
                     || !(S_ISREG(st.st_mode) || S_ISDIR(st.st_mode))) {
                    tlist = g_slist_next(tlist);
                    continue;
            }
这里跳过了全部的非普通文件类型的文件，
            /_ 获取文件类型图标 _/
            if (S_ISREG(st.st_mode))
                    pixbuf = rpixbuf;
            else if (S_ISDIR(st.st_mode))
                    pixbuf = dpixbuf;
            else
                    pixbuf = NULL;
           filesize = afs.ftwsize((char *)tlist->data);    这里调用AnalogFS::ftwsize来获取文件的大小，但是这里：
        DIR_ dir = opendir(dir_name);
        if(dir == NULL) {
                pwarning(_("opendir on \"%s\" failed: %s"), dir_name, strerror(errno));
                return 0;
        }
却只处理目录，导致返回的普通文件类型的大小全是0，因此没有办法发送单个文件

不知道是不是bug

**Comment by asule90** [comment]
this bug is still exist in Ubuntu 14.04 i use now.
debug shows :

iptux: Opendir() directory "/location/to/a/file.pdf" failed, Not a directory

Any help?

**Comment by lidaobing** [comment]
@asule90 what's the version you used in ubuntu 14.04? you install it with apt-get or install from the git master branch?

thanks.

**Comment by lidaobing** [comment]
@asule90 I pushed a new commit to master branch, it has a better log in this case, can you have a try on it?

thanks

**Comment by asule90** [comment]
@lidaobing thanks for the response.
i used synaptic package manager.

after your push, now i installed it from git with "Build from source" instruction
i'm using iptux (0.6.5) ubuntu and other user uses ipmsg windows

great, it works.
but sometimes i got this ,although the file was sent:

`(iptux:14048): Gtk-CRITICAL **: IA__gtk_widget_show: assertion 'GTK_IS_WIDGET (widget)' failed
(iptux:14048): GLib-CRITICAL **: Source ID 112 was not found when attempting to remove it`

**Comment by lidaobing** [comment]
@asule90 thanks, I think I can close this bug now.
and if you can use gdb, can you help got a backtrace for the critical message? if not, can you help make me know how to reproduce this bug?

thanks.
