### ISSUE TITLE
直接点关闭后，重新打开时报端口被占用

### ISSUE THREAD

**Issue by TivJsou** [iptux-src/iptux#40]
opensuse 13.2,KDE桌面。

直接点关闭后程序图形界面没了，托盘区也没有图标，但是在ps -u user命令中可以看到进程仍在运行。

重新打开程序报端口被占用。

建议关闭按钮改为最小化窗口。

**Comment by bubbless** [comment]
我也遇到了，终端里面运行iptux也没有报错信息出现
运行环境 `Archlinux + Xfce4` 
AUR中还是0.6.2，修改了PKGBUILD,安装了0.6.3还是一样的情况，局域网传文件麻烦了。

**Comment by lidaobing** [comment]
merged into #52
