### ISSUE TITLE
edge 通道版本无法操作设置

### ISSUE THREAD

**Issue by fenghuan1994** [iptux-src/iptux#418]
最新版本edge通道版本，没有设置菜单。
Ubuntu18.04系统

**Comment by fenghuan1994** [comment]
加了--devmode 重新安装后可以打开设置。但是发现无法设置enter 发送消息。即使已经选中了。也依旧需要ctrl+enter发送

**Comment by lidaobing** [comment]
> 最新版本edge通道版本，没有设置菜单。
> Ubuntu18.04系统

能给我一个全屏截图么？我在gnome和 xfce 下面都能看到

**Comment by lidaobing** [comment]
> 加了--devmode 重新安装后可以打开设置。但是发现无法设置enter 发送消息。即使已经选中了。也依旧需要ctrl+enter发送

放到 #419 了

**Comment by fenghuan1994** [comment]
可能我形容的不对。这个地方，点击无作用
![2021-04-07 18-56-49 的屏幕截图](https://user-images.githubusercontent.com/22291785/113856365-b675d000-97d3-11eb-8e7b-7e16b1904afe.png)

**Comment by lidaobing** [comment]
reproduced under Ubuntu 18.04

**Comment by lidaobing** [comment]
fixed in 1c217a9
