### ISSUE TITLE
Please add me as a collaborator

### ISSUE THREAD

**Issue by anthonyfok** [iptux-src/iptux#48]
Hello Daobing,

Please add me as a collaborator to this project.

No, I do not want to adopt iptux.  I am a perfect example of 三分钟热度, and suddenly got the urge to work on iptux because I saw a "removal from testing" notice and panicked, but otherwise, I tend to come and go randomly, leaving a package untouched for years until something alarms me to it.  :-)

But I would be very happy to be your little helper, i.e. a Collaborator in GitHub-speak, so that I can help sort out Issues and Pull Requests, and probably commit a tiny patch to fix minor problems, 偶尔的小修小补 is enough for me.  :-)

Many thanks!

Anthony

**Comment by lidaobing** [comment]
invited

**Comment by anthonyfok** [comment]
Thank you very much for your invitation, @lidaobing!  :-)
