### ISSUE TITLE
change name issue on Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by chiragBisag** [iptux-src/iptux#506]
dont have any options to change name on iptux please provide us option for change name of iptux

**Comment by YJPrakash** [comment]
Yes, the previous version has a preference option. how to change the chat preference save history and open chat dialog option?

**Comment by lidaobing** [comment]
It's a bug of old version, you can install snap version and/or forward this bug to https://bugs.launchpad.net/ubuntu/+source/iptux
