### ISSUE TITLE
FAILED: share/metainfo/io.github.iptux_src.iptux.metainfo.xml 

### ISSUE THREAD

**Issue by kero990** [iptux-src/iptux#509]
Compilation environment: debian10, arm64

Compilation has been stuck in
FAILED: share/metainfo/io.github.iptux_src.iptux.metainfo.xml
/usr/local/bin/meson --internal msgfmthelper --msgfmt=/usr/bin/msgfmt ../share/metainfo/io.github.iptux_src.iptux.metaininfo.xml share/metainfo/io.github.iptux_src. iptux.metaininfo.xml xml /root/iptux/po
/usr/bin/msgfmt: cannot locate ITS rules for ../share/metainfo/io.github.iptux_src.iptux.metainfo.xml

**Comment by ColorfulKun** [comment]
sudo apt-get install appstream;
