### ISSUE TITLE
Failed to bind the TCP/UDP port(2425)!

### ISSUE THREAD

**Issue by vipul-jain** [iptux-src/iptux#52]
How to configure it...?

**Comment by anthonyfok** [comment]
Hi @vipul-jain,

You probably have another copy of iptux already running.  Please read this thread about **iptux does not start: “Address already in use” error** at http://askubuntu.com/questions/448433/iptux-does-not-start-address-already-in-use-error for solution, and let us know if it works for you or not.

Cheers,
Anthony

**Comment by shameemcp** [comment]
it doesn't work

**Comment by shameemcp** [comment]
it doesn't work either,

**Comment by divyanshu-rawat** [comment]
Fatal Error!! Failed to bind the TCP/UDP port(2425) ! Address already in use.
I am encountering same issue after clearing   all instances of iptux from the command .

`killall iptux`

 And also manually tried closing port no 2425 

`sudo fuser 2425/tcp`

And then restarting iptux

**Comment by RohitKatre** [comment]
this is not working
