### ISSUE TITLE
"Sort by" Additional Options Needed [By User, By Host]

### ISSUE THREAD

**Issue by pharmankur** [iptux-src/iptux#524]
Using iptux 0.8.3 on Linux mint 21.2
In View, We have only two options for sorting of list viz. By Nickname, By IP.
Whereas we should have other sorting options as well viz. **By User, By Host** ( These options are available in **ipmsg** - the iptux equivalent in Windows ) 

It will make easier to identify ppl on network.

**Comment by pharmankur** [comment]
Thanks !
Waiting for release 0.8.6

**Comment by lidaobing** [comment]
you can try the edge version with snap.

```
$ snap switch --channel edge iptux
$ snap refresh
```

**Comment by lidaobing** [comment]
<img width="490" alt="image" src="https://github.com/iptux-src/iptux/assets/27529/a085a494-ed06-40df-b92d-5713f841dcf2">
<img width="483" alt="image" src="https://github.com/iptux-src/iptux/assets/27529/2f0978df-5ab2-4eaa-809d-466e92f965cd">
