### ISSUE TITLE
error from compile

### ISSUE THREAD

**Issue by xverizex** [iptux-src/iptux#58]
`MainWindow.cpp:1529:37: error: invalid conversion from ‘char’ to ‘const char*’ [-fpermissive]
         if (g_strcmp0(remaining,'\0'))
`

**Comment by xverizex** [comment]
fix
`if (g_strcmp0(remaining,(char *)'\0' )`

**Comment by xverizex** [comment]
https://github.com/iptux-src/iptux/blob/1a5a6c40c6cc6731148d773ef743b696aae0b53b/src/MainWindow.cpp#L1529
Please fix it.

**Comment by lidaobing** [comment]
@xverizex what's your compiler version?

**Comment by xverizex** [comment]
gcc version 7.1.1

**Comment by lidaobing** [comment]
fixed in #59
