### ISSUE TITLE
Debian bug report Bug#1071039: iptux FTBFS on 32bit with 64bit time_t

### ISSUE THREAD

**Issue by atzlinux** [iptux-src/iptux#581]
Please see: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1071039

The newest iptux version 0.9.1 build failed on some 32 bit arch.

One of  full build failed log is:

https://buildd.debian.org/status/fetch.php?pkg=iptux&arch=armhf&ver=0.9.1-1&stamp=1715595249&raw=0

Thanks!

**Comment by lidaobing** [comment]
ref: https://wiki.debian.org/CrossCompiling

**Comment by lidaobing** [comment]
Debian bookworm does not have this problem; only sid has, and that's why the CI does not error on this.
