### ISSUE TITLE
设置自动隐藏面板之后窗口无法显示了

### ISSUE THREAD

**Issue by hungtcs** [iptux-src/iptux#60]
设置自动隐藏面板之后每次启动都会自动隐藏`iptux`的窗口，收到消息可以听见提示音但是无法打开窗口，导致无法使用。

根据网上的帮助删除`~/.gconf/apps/iptux`和执行`gconftool-2 --recursive-unset /apps/iptux`也不管用。

-----
elementary OS 0.4.1 Loki (基于 "Ubuntu 16.04.3 LTS" 构建)

**Comment by lidaobing** [comment]
已经换成 jsoncpp, 如果需要的话可以直接删除 `$HOME/.iptux/config.json`
