### ISSUE TITLE
meson test TIMEOUT        30.01s   exit status 1

### ISSUE THREAD

**Issue by atzlinux** [iptux-src/iptux#611]
`
meson test
ninja: no work to do.
ninja: Entering directory `/home/atzlinux/devel/official/iptux/obj-x86_64-linux-gnu'
ninja: no work to do.
1/4 iptux utils unit test         OK              0.01s
2/4 iptux core unit test          OK              1.20s
3/4 iptux ui unit test            TIMEOUT        30.01s   exit status 1
>>> MALLOC_PERTURB_=39 LD_LIBRARY_PATH=/home/atzlinux/devel/official/iptux/obj-x86_64-linux-gnu/src/iptux-core:/usr/local/lib /home/atzlinux/devel/official/iptux/obj-x86_64-linux-gnu/src/iptux/libiptux_test

4/4 validate metainfo file        OK              0.06s

Ok:                 3   
Expected Fail:      0   
Fail:               0   
Unexpected Pass:    0   
Skipped:            0   
Timeout:            1   

Full log written to /home/atzlinux/devel/official/iptux/obj-x86_64-linux-gnu/meson-logs/testlog.txt

`

[testlog.txt](https://github.com/user-attachments/files/15949297/testlog.txt)

**Comment by lidaobing** [comment]
two bugs:

1. one UT is locale sensitive, it will failed under `LC_ALL=zh_CN.UTF-8` (#600 )
2. some UT will depends on environment: like open_url or open_file , which cause meson test timeout.
