### ISSUE TITLE
命令行下发送消息

### ISSUE THREAD

**Issue by aaronmaomao** [iptux-src/iptux#640]
可否通过调用源码中的一些api，封装一个命令行版本的iptux。是否可行，跪求作者大神赐教

**Comment by lidaobing** [comment]
And you check #545; after that issue has been implemented, you can also send msg from cmd.

**Comment by aaronmaomao** [comment]
> you could check this file: https://github.com/iptux-src/iptux/blob/master/examples/count-bot/main.cpp it's a sample on How to run iptux protocol(or ipmsg protocol) under CLI.

I got it, thanks.
