### ISSUE TITLE
Howto hide Iptux's taskbar icon.

### ISSUE THREAD

**Issue by CummingCowGirl** [iptux-src/iptux#641]
I was looking for a dead simple lan messenger cause my roommate needs it as simple as possible. I ran across Iptux. I like the app cause it's dead simple and the dialog box doesn't look out of date. The only issue I have with it is when I click the X to close it to the systray it also minimizes to the main panel. 

We are using Icons-Only Task Manager on the main panel on Arch with KDE Plasma desktop version 6.2.4 and would like to know if there is anyway  we can keep the systray icon while hiding the icon on our panels?

Iptux version 0.9.1-2

**Comment by lidaobing** [comment]
@CummingCowGirl you could test it with the snap edge version

**Comment by CummingCowGirl** [comment]
Thanks but what is the snap edge version?

**Comment by lidaobing** [comment]
@CummingCowGirl 

`sudo snap install iptux --edge`

ref: https://snapcraft.io/iptux

**Comment by CummingCowGirl** [comment]
OK tested and it still is on the taskbar. From it's behavior even though iptux has a systray icon when one clicks the close button on it's window it actually minimizes to the taskbar.

**Comment by lidaobing** [comment]
Hi @CummingCowGirl 

You need to enable this function in the preference dialog:
<img width="536" alt="image" src="https://github.com/user-attachments/assets/ceee2632-94c9-4afa-a3b6-98764a3bedff" />

After it is enabled, if you close all the windows, the taskbar will disappear.

<img width="1202" alt="image" src="https://github.com/user-attachments/assets/02ea6b1e-1188-4723-94b4-aa79b18b2a2f" />

**Comment by CummingCowGirl** [comment]
I do not have that.

![Screenshot_20250101_094800](https://github.com/user-attachments/assets/086eabd1-9cf7-4890-88dd-62168a4f85c6)

**Comment by lidaobing** [comment]
@CummingCowGirl 

I sounds that you are not running the snap version.

try run `snap run iptux` in console.

Thanks,

**Comment by CummingCowGirl** [comment]
I uninstalled the AUR version and then installed the Snap version. Just closed it, ran your command and I get the same thing.

**Comment by lidaobing** [comment]
Hi @CummingCowGirl ,

Do you mean you still can't get the new feature? If it is, please show me the version with following command

```
$ snap list iptux
Name   Version               Rev  Tracking     Publisher  Notes
iptux  v0.9.3+git14.0b95385  732  latest/edge  lidaobing  -
```

Thanks,
