### ISSUE TITLE
CentOS and RHEL安装方式

### ISSUE THREAD

**Issue by lxhbs** [iptux-src/iptux#68]
sudo yum install git gtk2-devel glib2-devel GConf2-devel gstreamer1-devel gcc gcc-c++ make cmake3
sudo yum remove cmake
sudo ln -s /usr/bin/cmake3 /usr/bin/cmake

git clone git://github.com/iptux-src/iptux.git
cd iptux
mkdir build && cd build && cmake .. && make
sudo make install

sudo firewall-cmd --permanent --zone=public --add-port=2425/tcp
sudo firewall-cmd --permanent --zone=public --add-port=2425/udp
sudo firewall-cmd --complete-reload

iptux

由于只调用/usr/bin/cmake，又要求cmake版本为3，所以做了个软链接。最后是开防火墙2425端口的TCP和UDP。
以上在CentOS 7下成功安装，理论上RHEL和Fedora方式相同，未验证。

**Comment by lidaobing** [comment]
moved to https://github.com/iptux-src/iptux/wiki/CentOS-and-RHEL%E5%AE%89%E8%A3%85%E6%96%B9%E5%BC%8F
